GET http://localhost:3003/character

###

PUT http://localhost:3003/character
Content-Type: application/json

{
    "name":"Juggernaut",
    "gender":"MALE",
    "description": "O irmão do Prof X!!!"
}